version: '2'
services:
  concourse:
    build: .
    #dockerfile: concourse.Dockerfile
    privileged: true
    ports:
     - "8080:8080"
    dns: 8.8.8.8
  sonarqube:
    image: sonarqube
    ports:
     - "9000:9000"
     - "9092:9092"
